name: Publish Snapshots

on:
  push:
    branches:
      - 'main'
concurrency:
  group: ci-snapshots
  cancel-in-progress: true

jobs:
  release:
    name: Publish snapshots on Sonatype OSS
    if: github.repository == 'murdos/easy-random-protobuf'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_PORTAL_USERNAME
          server-password: CENTRAL_PORTAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Build and publish
        run: mvn deploy -ntp --batch-mode -P release
        env:
          CENTRAL_PORTAL_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
